#!/usr/bin/env python3
"""
Terminal Discord Rich Presence Service
Lightweight, privacy-focused Discord RPC for Windows Terminal, PowerShell, and CMD.
"""

import json
import os
import sys
import time
import uuid
import struct
import tempfile
import socket
from pathlib import Path

# IPC Opcodes
OP_HANDSHAKE = 0
OP_FRAME = 1
OP_CLOSE = 2
OP_PING = 3
OP_PONG = 4

LOCK_PORT = 64321
_LOCK_SOCKET = None  # Global handle to prevent garbage collection releasing lock socket

def ensure_single_instance():
    """
    Ensures that only one instance of terminal_rpc.py runs at a time.
    Binds a local socket port as a mutex lock and retains the global reference.
    """
    global _LOCK_SOCKET
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        s.bind(("127.0.0.1", LOCK_PORT))
        s.listen(1)
        _LOCK_SOCKET = s
        return True
    except Exception:
        print("[Notice] Another instance of Terminal Discord Presence is already running. Exiting.")
        sys.exit(0)

def get_state_file_path():
    """Get cross-platform or Windows temp path for shell state sharing."""
    temp_dir = tempfile.gettempdir()
    return os.path.join(temp_dir, "discord_terminal_state.json")

def sanitize_path(path_str, privacy_mode="folder"):
    """
    Sanitizes file path based on privacy mode.
    Modes:
      - 'folder': returns only the current folder name (e.g. 'my-project')
      - 'full': replaces user home directory with '~' and uses forward slashes
      - 'hidden': returns fixed generic text
    """
    if not path_str or privacy_mode == "hidden":
        return "Workspace"

    path_str = path_str.replace("\\", "/")
    if path_str.endswith("/") and len(path_str) > 1 and not path_str.endswith(":/"):
        path_str = path_str.rstrip("/")

    path_obj = Path(path_str)

    if privacy_mode == "folder":
        folder_name = path_obj.name
        if not folder_name or folder_name.endswith(":"):
            return path_str
        return folder_name

    if privacy_mode == "full":
        home = str(Path.home()).replace("\\", "/")
        if path_str.startswith(home):
            path_str = "~" + path_str[len(home):]
        return path_str

    return path_obj.name or path_str

def load_config(config_path="config.json"):
    """Loads configuration from JSON file or returns defaults."""
    default_config = {
        "client_id": "1234567890123456789",
        "privacy_mode": "folder",
        "update_interval": 3,
        "show_tabs": True,
        "show_elapsed": True,
        "show_active_shell": True,
        "default_shell": "PowerShell",
        "emojis": {
            "powershell": "⚡",
            "cmd": "💻",
            "wsl": "🐧",
            "terminal": "🖥️",
            "folder": "📁",
            "idle": "💤"
        },
        "assets": {
            "large_image": "terminal_main",
            "large_text": "Console",
            "powershell_small_image": "powershell_icon",
            "powershell_small_text": "PowerShell",
            "cmd_small_image": "cmd_icon",
            "cmd_small_text": "Command Prompt",
            "wsl_small_image": "wsl_icon",
            "wsl_small_text": "WSL (Linux)",
            "terminal_small_image": "terminal_icon",
            "terminal_small_text": "Windows Terminal"
        }
    }

    if os.path.exists(config_path):
        try:
            with open(config_path, "r", encoding="utf-8") as f:
                user_config = json.load(f)
                default_config.update(user_config)
        except Exception as e:
            print(f"[Warning] Failed to load {config_path}: {e}")

    return default_config

def read_shell_state(state_path=None):
    """Reads state file generated by shell profile hooks."""
    if state_path is None:
        state_path = get_state_file_path()

    if os.path.exists(state_path):
        try:
            with open(state_path, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception:
            pass
    return None

def format_status(active_shells, state_data, config):
    """
    Formats details, state, and asset info for Discord activity payload.
    Uses dynamic state from shell hook without static directory fallbacks.
    """
    emojis = config.get("emojis", {})
    assets = config.get("assets", {})
    privacy = config.get("privacy_mode", "folder")

    # Determine shell type
    shell_name = "PowerShell"
    small_image = assets.get("powershell_small_image", "powershell_icon")
    small_text = assets.get("powershell_small_text", "PowerShell")
    shell_emoji = emojis.get("powershell", "⚡")

    if state_data and "shell" in state_data:
        raw_shell = str(state_data["shell"]).lower()
        if "cmd" in raw_shell:
            shell_name = "CMD"
            small_image = assets.get("cmd_small_image", "cmd_icon")
            small_text = assets.get("cmd_small_text", "Command Prompt")
            shell_emoji = emojis.get("cmd", "💻")
        elif "wsl" in raw_shell or "bash" in raw_shell or "zsh" in raw_shell:
            shell_name = "WSL"
            small_image = assets.get("wsl_small_image", "wsl_icon")
            small_text = assets.get("wsl_small_text", "WSL (Linux)")
            shell_emoji = emojis.get("wsl", "🐧")
        elif "terminal" in raw_shell:
            shell_name = "Windows Terminal"
            small_image = assets.get("terminal_small_image", "terminal_icon")
            small_text = assets.get("terminal_small_text", "Windows Terminal")
            shell_emoji = emojis.get("terminal", "🖥️")
    elif active_shells:
        shells_lower = [s.lower() for s in active_shells]
        if any("cmd" in s for s in shells_lower):
            shell_name = "CMD"
            small_image = assets.get("cmd_small_image", "cmd_icon")
            small_text = assets.get("cmd_small_text", "Command Prompt")
            shell_emoji = emojis.get("cmd", "💻")
        elif any("windowsterminal" in s or "wt.exe" in s for s in shells_lower):
            shell_name = "Windows Terminal"
            small_image = assets.get("terminal_small_image", "terminal_icon")
            small_text = assets.get("terminal_small_text", "Windows Terminal")
            shell_emoji = emojis.get("terminal", "🖥️")
        elif any("wsl" in s or "bash" in s for s in shells_lower):
            shell_name = "WSL"
            small_image = assets.get("wsl_small_image", "wsl_icon")
            small_text = assets.get("wsl_small_text", "WSL (Linux)")
            shell_emoji = emojis.get("wsl", "🐧")

    # Tab count calculation: count user interactive shells
    tab_count = len(active_shells) if active_shells else 1
    tab_str = f" ({tab_count} tab{'s' if tab_count > 1 else ''})" if config.get("show_tabs") and tab_count > 1 else ""

    # User context and CWD calculation from state_data
    cwd = state_data.get("cwd") if state_data else None
    user_ctx = state_data.get("user") if state_data else None
    folder_emoji = emojis.get("folder", "📁")

    if cwd:
        sanitized_cwd = sanitize_path(cwd, privacy)
        if user_ctx:
            state_str = f"{folder_emoji} {user_ctx} {sanitized_cwd}"
        else:
            state_str = f"{folder_emoji} {sanitized_cwd}"
    else:
        state_str = f"{folder_emoji} {user_ctx if user_ctx else 'Interactive Shell'}"

    details_str = f"{shell_emoji} {shell_name}{tab_str}"

    return {
        "details": details_str,
        "state": state_str,
        "small_image": small_image,
        "small_text": small_text
    }

class DiscordIPC:
    """Handles low-level IPC socket/pipe communication with Discord Client."""
    def __init__(self, client_id):
        self.client_id = str(client_id)
        self.handle = None

    def _get_pipe_path(self, i=0):
        if sys.platform == "win32":
            return f"\\\\.\\pipe\\discord-ipc-{i}"
        else:
            env_vars = ["XDG_RUNTIME_DIR", "TMPDIR", "TMP", "TEMP"]
            for var in env_vars:
                path = os.environ.get(var)
                if path and os.path.exists(path):
                    return os.path.join(path, f"discord-ipc-{i}")
            return f"/tmp/discord-ipc-{i}"

    def connect(self):
        for i in range(10):
            pipe_path = self._get_pipe_path(i)
            try:
                if sys.platform == "win32":
                    self.handle = open(pipe_path, "r+b", buffering=0)
                else:
                    import socket as py_socket
                    s = py_socket.socket(py_socket.AF_UNIX, py_socket.SOCK_STREAM)
                    s.connect(pipe_path)
                    self.handle = s

                # Perform Handshake
                self._send(OP_HANDSHAKE, {"v": 1, "client_id": self.client_id})
                op, resp = self._read()
                if op == OP_FRAME and resp.get("evt") == "READY":
                    print(f"[IPC] Connected to Discord via {pipe_path}")
                    return True
            except Exception:
                if self.handle:
                    self.close()
                continue
        return False

    def _send(self, opcode, payload):
        data = json.dumps(payload).encode("utf-8")
        header = struct.pack("<II", opcode, len(data))
        if sys.platform == "win32":
            self.handle.write(header + data)
            self.handle.flush()
        else:
            self.handle.sendall(header + data)

    def _read(self):
        if sys.platform == "win32":
            header = self.handle.read(8)
            if not header or len(header) < 8:
                return None, None
            opcode, length = struct.unpack("<II", header)
            data = b""
            while len(data) < length:
                chunk = self.handle.read(length - len(data))
                if not chunk:
                    break
                data += chunk
            return opcode, json.loads(data.decode("utf-8"))
        else:
            header = self.handle.recv(8)
            if not header or len(header) < 8:
                return None, None
            opcode, length = struct.unpack("<II", header)
            data = b""
            while len(data) < length:
                chunk = self.handle.recv(length - len(data))
                if not chunk:
                    break
                data += chunk
            return opcode, json.loads(data.decode("utf-8"))

    def set_activity(self, activity_data, start_time=None):
        payload = {
            "cmd": "SET_ACTIVITY",
            "args": {
                "pid": os.getpid(),
                "activity": {
                    "details": activity_data["details"],
                    "state": activity_data["state"],
                    "assets": {
                        "large_image": activity_data.get("large_image", "terminal_main"),
                        "large_text": activity_data.get("large_text", "Console"),
                    }
                }
            },
            "nonce": str(uuid.uuid4())
        }

        if activity_data.get("small_image"):
            payload["args"]["activity"]["assets"]["small_image"] = activity_data["small_image"]
        if activity_data.get("small_text"):
            payload["args"]["activity"]["assets"]["small_text"] = activity_data["small_text"]

        if start_time:
            payload["args"]["activity"]["timestamps"] = {"start": int(start_time)}

        self._send(OP_FRAME, payload)

    def close(self):
        if self.handle:
            try:
                if sys.platform == "win32":
                    self.handle.close()
                else:
                    self.handle.close()
            except Exception:
                pass
            self.handle = None

def scan_running_terminals():
    """
    Detects active user terminal and shell processes (PowerShell, CMD, Windows Terminal, WSL).
    Excludes background host helpers (conhost, wslhost, tasklist, etc.) to count true interactive tabs accurately.
    """
    running_shells = []
    # Primary interactive shells that constitute open tabs
    primary_shells = ["powershell.exe", "pwsh.exe", "cmd.exe", "windowsterminal.exe", "bash", "zsh"]

    if sys.platform == "win32":
        try:
            import subprocess
            output = subprocess.check_output("tasklist /FO CSV /NH", shell=True).decode("utf-8", errors="ignore")
            for line in output.splitlines():
                if not line.strip():
                    continue
                parts = line.split('","')
                if parts:
                    proc_name = parts[0].replace('"', '').strip().lower()
                    if proc_name in primary_shells:
                        running_shells.append(proc_name)
        except Exception:
            pass
    else:
        try:
            import subprocess
            output = subprocess.check_output(["ps", "-ax", "-o", "comm="]).decode("utf-8", errors="ignore")
            for line in output.splitlines():
                proc_name = os.path.basename(line.strip()).lower()
                if proc_name in primary_shells:
                    running_shells.append(proc_name)
        except Exception:
            pass

    return running_shells

def main():
    ensure_single_instance()

    config = load_config()
    client_id = config.get("client_id")
    update_interval = config.get("update_interval", 3)
    start_time = time.time() if config.get("show_elapsed") else None

    print(f"Starting Terminal Discord Rich Presence... (Client ID: {client_id})")

    ipc = DiscordIPC(client_id)
    connected = False

    try:
        while True:
            if not connected:
                connected = ipc.connect()
                if not connected:
                    time.sleep(10)
                    continue

            active_shells = scan_running_terminals()
            state_data = read_shell_state()

            status = format_status(active_shells, state_data, config)
            status["large_image"] = config.get("assets", {}).get("large_image", "terminal_main")
            status["large_text"] = config.get("assets", {}).get("large_text", "Console")

            try:
                ipc.set_activity(status, start_time=start_time)
            except Exception as e:
                print(f"[IPC Error] Disconnected: {e}")
                connected = False
                ipc.close()

            time.sleep(update_interval)
    except KeyboardInterrupt:
        print("\nStopping Terminal Discord Presence...")
    finally:
        ipc.close()

if __name__ == "__main__":
    main()
